apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: us-central1-docker.pkg.dev/mooninsuarancecw/mooninsurance-repo/notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
