apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator-service
spec:
  schedule: "*/1 * * * *"  # Every 1 minute (for testing)
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: aggregator-service
        spec:
          restartPolicy: OnFailure
          containers:
          - name: aggregator-service
            image: us-central1-docker.pkg.dev/mooninsuarancecw/mooninsurance-repo/aggregator-service:latest
            imagePullPolicy: Always
            ports:
            - containerPort: 80
            env:
            - name: INTEGRATION_SERVICE_URL
              value: "http://integration-service/sales/"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service/notify/"
            - name: REDSHIFT_HOST
              value: "<your-redshift-cluster-url>"
            - name: REDSHIFT_DB
              value: "<your-redshift-db-name>"
            - name: REDSHIFT_USER
              value: "<your-redshift-username>"
            - name: REDSHIFT_PASSWORD
              value: "<your-redshift-password>"
