apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator-service
spec:
  schedule: "*/1 * * * *"  # Every 1 minute (for testing)
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: aggregator-service
        spec:
          restartPolicy: OnFailure
          containers:
          - name: aggregator-service
            image: us-central1-docker.pkg.dev/mooninsuarancecw/mooninsurance-repo/aggregator-service:latest
            imagePullPolicy: Always
            ports:
            - containerPort: 80
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/key.json
            - name: GCP_PROJECT_ID
              value: mooninsuarancecw
            - name: BQ_DATASET
              value: mooninsurance_metrics
            - name: BQ_TABLE
              value: top_agent_sales
            - name: INTEGRATION_SERVICE_URL
              value: "http://integration-service/sales/"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service/notify/"
            volumeMounts:
            - name: bq-service-account
              mountPath: /var/secrets
              readOnly: true
          volumes:
          - name: bq-service-account
            secret:
              secretName: bq-service-account-key
