apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
  labels:
    app: aggregator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
      - name: aggregator-service
        image: gcr.io/<your-gcp-project-id>/aggregator-service:latest
        ports:
        - containerPort: 80
        env:
        - name: INTEGRATION_SERVICE_URL
          value: "http://integration-service/sales/"  # Kubernetes service DNS name
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  selector:
    app: aggregator-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
