apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  labels:
    app: integration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
      - name: integration-service
        image: gcr.io/<your-gcp-project-id>/integration-service:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "sqlite:///./sales_db.db"
---
apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  selector:
    app: integration-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
