name: Deploy All Microservices to GKE

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  deploy:
    name: Build, Push, and Deploy All Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: mooninsuarancecw
          export_default_credentials: true

      - name: Authenticate Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      #########################
      # Agent Service
      #########################
      - name: Build Agent Service Docker image
        run: docker build -t us-central1-docker.pkg.dev/mooninsuarancecw/mooninsurance-repo/agent-service:latest ./agent-service

      - name: Push Agent Service image
        run: docker push us-central1-docker.pkg.dev/mooninsuarancecw/mooninsurance-repo/agent-service:latest

      #########################
      # Integration Service
      #########################
      - name: Build Integration Service Docker image
        run: docker build -t us-central1-docker.pkg.dev/mooninsuarancecw/mooninsurance-repo/integration-service:latest ./integration-service

      - name: Push Integration Service image
        run: docker push us-central1-docker.pkg.dev/mooninsuarancecw/mooninsurance-repo/integration-service:latest

      #########################
      # Notification Service
      #########################
      - name: Build Notification Service Docker image
        run: docker build -t us-central1-docker.pkg.dev/mooninsuarancecw/mooninsurance-repo/notification-service:latest ./notification-service

      - name: Push Notification Service image
        run: docker push us-central1-docker.pkg.dev/mooninsuarancecw/mooninsurance-repo/notification-service:latest

      #########################
      # Aggregator Service
      #########################
      - name: Build Aggregator Service Docker image
        run: docker build -t us-central1-docker.pkg.dev/mooninsuarancecw/mooninsurance-repo/aggregator-service:latest ./aggregator-service

      - name: Push Aggregator Service image
        run: docker push us-central1-docker.pkg.dev/mooninsuarancecw/mooninsurance-repo/aggregator-service:latest

      #########################
      # Deploy to GKE
      #########################
      - name: Configure kubectl with GKE credentials
        run: gcloud container clusters get-credentials mooninsurance-cluster --zone us-central1-c

      - name: Apply Agent Service Deployment
        run: kubectl apply -f agent-service/deployment.yaml

      - name: Apply Integration Service Deployment
        run: kubectl apply -f integration-service/deployment.yaml

      - name: Apply Notification Service Deployment
        run: kubectl apply -f notification-service/deployment.yaml

      - name: Apply Aggregator CronJob
        run: |
          kubectl delete cronjob aggregator-service --ignore-not-found
          kubectl apply -f aggregator-service/cronjob.yaml
